name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@v2

    - name: Install dependencies
      run: uv sync --extra dev --extra plot

    - name: Run tests with coverage
      run: |
        uv run pytest --cov=src/windforecast

    - name: Upload coverage to Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: coverallsapp/github-action@v2
